### ISSUE TITLE
Socket timed out exception while connecting to SMP when doing multiple transactions

### ISSUE THREAD

**Issue by dhixon** [phax/peppol-commons#22]
1. Performed some 20 requests
2. Notice that only 19 worked and one out of 20 transactions failed with "Request send error Socket operation timed out before it could be completed"

Observed this stack trace in the request process log:
        ...
Caused by: com.ibm.b2b.comms.http.sender.exception.ConnectFailedException: Connection Failure for connection properties [RemoteHost:B-cddd3d2e86e5fbd4cdabf61d42da5c79.iso6523-actorid-upis.acc.edelivery.tech.ec.europa.eu,RemotePort:80,Localhost:9.113.28.69]
        at com.ibm.b2b.comms.http.sender.impl.channelfw.Worker.doConnectAndSend(Worker.java:112)
        at com.ibm.b2b.comms.http.sender.impl.SenderImpl.send(SenderImpl.java:54)
        at Proxy88cb390e_44d8_4241_b85b_34cf8126c2dd.send(Unknown Source)
        at Proxy88cb390e_44d8_4241_b85b_34cf8126c2dd.send(Unknown Source)
        at Proxy57bf273e_2ad9_4144_a944_09eaa56d866c.send(Unknown Source)
        at com.ibm.b2b.comms.emb.handler.impl.HTTPSenderHandler.process(HTTPSenderHandler.java:94)
        ... 16 more
Caused by: java.net.SocketTimeoutException: Socket operation timed out before it could be completed
        at com.ibm.b2b.ws.tcpchannel.internal.ConnectChannelSelector.checkForTimeouts(ConnectChannelSelector.java:230)
        at com.ibm.b2b.ws.tcpchannel.internal.ChannelSelector.run(ChannelSelector.java:237)
        ... 1 more

**Comment by dhixon** [comment]
Wrong product.  Closing issue.
