### ISSUE TITLE
SMP Dynamic Discovery Error 

### ISSUE THREAD

**Issue by jianweng11** [phax/peppol-commons#51]
Dear Philip and Team,

The SMP query can be accessed through a browser, but an error is encountered during SMK dynamic discovery. Can you guide me on resolving this issue? The log is provided below for your reference.

`[2024-02-29T15:24:29,437] [phase4-peppol] [INFO ] [https-jsse-nio-443-exec-1] Performing SMP query at 'GET http://B-bb826466dfe7f7db3786cdaf92b3eea3.iso6523-actorid-upis.acc.edelivery.tech.ec.europa.eu/iso6523-actorid-upis%3A%3A0230%3A99202003251658t/services/busdox-docid-qns%3A%3Aurn%3Aoasis%3Anames%3Aspecification%3Aubl%3Aschema%3Axsd%3AInvoice-2%3A%3AInvoice%23%23urn%3Acen.eu%3Aen16931%3A2017%23compliant%23urn%3Afdc%3Apeppol.eu%3A2017%3Apoacc%3Abilling%3A3.0%3A%3A2.1' -- com.helger.smpclient.httpclient.AbstractGenericSMPClient.executeRequest(AbstractGenericSMPClient.java:362)
[2024-02-29T15:24:30,339] [phase4-peppol] [ERROR] [https-jsse-nio-443-exec-1] Error performing SMP query: org.apache.hc.client5.http.ClientProtocolException - null -- com.helger.smpclient.httpclient.AbstractGenericSMPClient.executeRequest(AbstractGenericSMPClient.java:370)
[2024-02-29T15:24:30,339] [phase4-peppol] [ERROR] [https-jsse-nio-443-exec-1] Exception sending AS4 user message -- com.helger.phase4.sender.AbstractAS4UserMessageBuilder.lambda$1(AbstractAS4UserMessageBuilder.java:764)
com.helger.phase4.dynamicdiscovery.Phase4SMPException: Failed to resolve SMP endpoint (iso6523-actorid-upis::0230:99202003251658t, busdox-docid-qns::urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0::2.1, cenbii-procid-ubl::urn:fdc:peppol.eu:2017:poacc:billing:01:1.0, peppol-transport-as4-v2_0)
	at com.helger.phase4.dynamicdiscovery.AS4EndpointDetailProviderPeppol.init(AS4EndpointDetailProviderPeppol.java:216) ~[phase4-dynamic-discovery-2.7.5-SNAPSHOT.jar:?]
	at com.helger.phase4.peppol.Phase4PeppolSender$AbstractPeppolUserMessageBuilder.finishFields(Phase4PeppolSender.java:790) ~[phase4-peppol-client-2.7.5-SNAPSHOT.jar:?]
	at com.helger.phase4.peppol.Phase4PeppolSender$Builder.finishFields(Phase4PeppolSender.java:1344) ~[phase4-peppol-client-2.7.5-SNAPSHOT.jar:?]
	at com.helger.phase4.sender.AbstractAS4MessageBuilder.sendMessage(AbstractAS4MessageBuilder.java:831) ~[phase4-lib-2.7.5-SNAPSHOT.jar:?]
	at com.helger.phase4.sender.AbstractAS4UserMessageBuilder.sendMessageAndCheckForReceipt(AbstractAS4UserMessageBuilder.java:798) ~[phase4-lib-2.7.5-SNAPSHOT.jar:?]
	at com.helger.phase4.sender.AbstractAS4UserMessageBuilder.sendMessageAndCheckForReceipt(AbstractAS4UserMessageBuilder.java:764) ~[phase4-lib-2.7.5-SNAPSHOT.jar:?]
	at com.smartfund.peppol.rest.resource.SendMessageResource._sendPeppolMessage(SendMessageResource.java:252) ~[classes/:2.7.5-SNAPSHOT]
	at com.smartfund.peppol.rest.resource.SendMessageResource.sendMessage(SendMessageResource.java:146) ~[classes/:2.7.5-SNAPSHOT]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-3.1.5.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146) ~[jersey-server-3.1.5.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189) ~[jersey-server-3.1.5.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[jersey-server-3.1.5.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93) ~[jersey-server-3.1.5.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[jersey-server-3.1.5.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[jersey-server-3.1.5.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[jersey-server-3.1.5.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261) ~[jersey-server-3.1.5.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-3.1.5.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-3.1.5.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-3.1.5.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-3.1.5.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-3.1.5.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[jersey-common-3.1.5.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240) ~[jersey-server-3.1.5.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697) ~[jersey-server-3.1.5.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[jersey-container-servlet-core-3.1.5.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[jersey-container-servlet-core-3.1.5.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:357) ~[jersey-container-servlet-core-3.1.5.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311) ~[jersey-container-servlet-core-3.1.5.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[jersey-container-servlet-core-3.1.5.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[catalina.jar:10.1.19]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[catalina.jar:10.1.19]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-websocket.jar:10.1.19]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[catalina.jar:10.1.19]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[catalina.jar:10.1.19]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[catalina.jar:10.1.19]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[catalina.jar:10.1.19]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) ~[catalina.jar:10.1.19]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[catalina.jar:10.1.19]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[catalina.jar:10.1.19]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673) ~[catalina.jar:10.1.19]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[catalina.jar:10.1.19]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) ~[catalina.jar:10.1.19]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) ~[tomcat-coyote.jar:10.1.19]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-coyote.jar:10.1.19]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896) ~[tomcat-coyote.jar:10.1.19]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744) ~[tomcat-coyote.jar:10.1.19]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-coyote.jar:10.1.19]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-util.jar:10.1.19]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-util.jar:10.1.19]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-util.jar:10.1.19]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: com.helger.smpclient.exception.SMPClientBadResponseException: Error in validating signature returned from SMP server
	at com.helger.smpclient.httpclient.SMPHttpResponseHandlerSigned.handleEntity(SMPHttpResponseHandlerSigned.java:334) ~[peppol-smp-client-9.3.1-SNAPSHOT.jar:9.3.1-SNAPSHOT]
	at com.helger.smpclient.httpclient.AbstractSMPResponseHandler.handleResponse(AbstractSMPResponseHandler.java:86) ~[peppol-smp-client-9.3.1-SNAPSHOT.jar:9.3.1-SNAPSHOT]
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:247) ~[httpclient5-5.2.3.jar:5.2.3]
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188) ~[httpclient5-5.2.3.jar:5.2.3]
	at com.helger.httpclient.HttpClientManager.execute(HttpClientManager.java:137) ~[ph-httpclient-10.1.7.jar:10.1.7]
	at com.helger.smpclient.httpclient.AbstractGenericSMPClient.executeRequest(AbstractGenericSMPClient.java:363) ~[peppol-smp-client-9.3.1-SNAPSHOT.jar:9.3.1-SNAPSHOT]
	at com.helger.smpclient.httpclient.AbstractGenericSMPClient.executeGenericRequest(AbstractGenericSMPClient.java:401) ~[peppol-smp-client-9.3.1-SNAPSHOT.jar:9.3.1-SNAPSHOT]
	at com.helger.smpclient.peppol.SMPClientReadOnly.getServiceMetadata(SMPClientReadOnly.java:551) ~[peppol-smp-client-9.3.1-SNAPSHOT.jar:9.3.1-SNAPSHOT]
	at com.helger.smpclient.peppol.SMPClientReadOnly.getServiceMetadataOrNull(SMPClientReadOnly.java:639) ~[peppol-smp-client-9.3.1-SNAPSHOT.jar:9.3.1-SNAPSHOT]
	at com.helger.smpclient.peppol.ISMPServiceMetadataProvider.getEndpointAt(ISMPServiceMetadataProvider.java:180) ~[peppol-smp-client-9.3.1-SNAPSHOT.jar:9.3.1-SNAPSHOT]
	at com.helger.smpclient.peppol.ISMPServiceMetadataProvider.getEndpoint(ISMPServiceMetadataProvider.java:126) ~[peppol-smp-client-9.3.1-SNAPSHOT.jar:9.3.1-SNAPSHOT]
	at com.helger.phase4.dynamicdiscovery.AS4EndpointDetailProviderPeppol.init(AS4EndpointDetailProviderPeppol.java:188) ~[phase4-dynamic-discovery-2.7.5-SNAPSHOT.jar:?]
	... 53 more
Caused by: javax.xml.crypto.MarshalException: It is forbidden to use algorithm http://www.w3.org/2000/09/xmldsig#rsa-sha1 when secure validation is enabled
	at java.xml.crypto/org.jcp.xml.dsig.internal.dom.DOMSignedInfo.<init>(DOMSignedInfo.java:155) ~[java.xml.crypto:?]
	at java.xml.crypto/org.jcp.xml.dsig.internal.dom.DOMXMLSignature.<init>(DOMXMLSignature.java:141) ~[java.xml.crypto:?]
	at java.xml.crypto/org.jcp.xml.dsig.internal.dom.DOMXMLSignatureFactory.unmarshal(DOMXMLSignatureFactory.java:193) ~[java.xml.crypto:?]
	at java.xml.crypto/org.jcp.xml.dsig.internal.dom.DOMXMLSignatureFactory.unmarshalXMLSignature(DOMXMLSignatureFactory.java:148) ~[java.xml.crypto:?]
	at com.helger.smpclient.httpclient.SMPHttpResponseHandlerSigned.checkSignature(SMPHttpResponseHandlerSigned.java:216) ~[peppol-smp-client-9.3.1-SNAPSHOT.jar:9.3.1-SNAPSHOT]
	at com.helger.smpclient.httpclient.SMPHttpResponseHandlerSigned._checkSignature(SMPHttpResponseHandlerSigned.java:296) ~[peppol-smp-client-9.3.1-SNAPSHOT.jar:9.3.1-SNAPSHOT]
	at com.helger.smpclient.httpclient.SMPHttpResponseHandlerSigned.handleEntity(SMPHttpResponseHandlerSigned.java:319) ~[peppol-smp-client-9.3.1-SNAPSHOT.jar:9.3.1-SNAPSHOT]
	at com.helger.smpclient.httpclient.AbstractSMPResponseHandler.handleResponse(AbstractSMPResponseHandler.java:86) ~[peppol-smp-client-9.3.1-SNAPSHOT.jar:9.3.1-SNAPSHOT]
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:247) ~[httpclient5-5.2.3.jar:5.2.3]
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188) ~[httpclient5-5.2.3.jar:5.2.3]
	at com.helger.httpclient.HttpClientManager.execute(HttpClientManager.java:137) ~[ph-httpclient-10.1.7.jar:10.1.7]
	at com.helger.smpclient.httpclient.AbstractGenericSMPClient.executeRequest(AbstractGenericSMPClient.java:363) ~[peppol-smp-client-9.3.1-SNAPSHOT.jar:9.3.1-SNAPSHOT]
	at com.helger.smpclient.httpclient.AbstractGenericSMPClient.executeGenericRequest(AbstractGenericSMPClient.java:401) ~[peppol-smp-client-9.3.1-SNAPSHOT.jar:9.3.1-SNAPSHOT]
	at com.helger.smpclient.peppol.SMPClientReadOnly.getServiceMetadata(SMPClientReadOnly.java:551) ~[peppol-smp-client-9.3.1-SNAPSHOT.jar:9.3.1-SNAPSHOT]
	at com.helger.smpclient.peppol.SMPClientReadOnly.getServiceMetadataOrNull(SMPClientReadOnly.java:639) ~[peppol-smp-client-9.3.1-SNAPSHOT.jar:9.3.1-SNAPSHOT]
	at com.helger.smpclient.peppol.ISMPServiceMetadataProvider.getEndpointAt(ISMPServiceMetadataProvider.java:180) ~[peppol-smp-client-9.3.1-SNAPSHOT.jar:9.3.1-SNAPSHOT]
	at com.helger.smpclient.peppol.ISMPServiceMetadataProvider.getEndpoint(ISMPServiceMetadataProvider.java:126) ~[peppol-smp-client-9.3.1-SNAPSHOT.jar:9.3.1-SNAPSHOT]
	at com.helger.phase4.dynamicdiscovery.AS4EndpointDetailProviderPeppol.init(AS4EndpointDetailProviderPeppol.java:188) ~[phase4-dynamic-discovery-2.7.5-SNAPSHOT.jar:?]
	... 53 more
[2024-02-29T15:24:30,340] [phase4-peppol] [INFO ] [https-jsse-nio-443-exec-1] Peppol client send result: TRANSPORT_ERROR -- com.smartfund.peppol.rest.resource.SendMessageResource._sendPeppolMessage(SendMessageResource.java:253)`

**Comment by phax** [comment]
The root problem is:
```
Caused by: javax.xml.crypto.MarshalException: It is forbidden to use algorithm http://www.w3.org/2000/09/xmldsig#rsa-sha1 when secure validation is enabled at java.xml.crypto/org.jcp.xml.dsig.internal.dom.DOMSignedInfo.<init>(DOMSignedInfo.java:155)
```
Since Java 17 the usage of the SHA-1 signature algorithm was deprecated.
In the short term, please use `smpClient.setSecureValidation (false)` to disable the check. This simply avoids the "deprecation check" but of course checks the signature etc.
In the mid term, by upgrading to the Peppol SMP 1.3.0 specification, the algorithm SHA-1 is replaced with SHA-256 so that is no longer an issue. The Peppol SMP 1.3.0 specification will be mandatory by June 1st, 2024 - see https://docs.peppol.eu/edelivery/

**Comment by jianweng11** [comment]
Dear @phax 

Thank you very much and the problem has been resolved. Noted that the SHA-1 algorithm will be replaced with SHA-256

Thanks.
